name: Deploy Docsify to GitHub Pages

on:
  push:
    branches:
      - main  # Updated from 'master' to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2  # This action does not depend on Node.js version
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build Docsify site
        run: docsify build .  # This is typically not needed for Docsify as it usually doesn't require a build step, but included for completeness

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
